/** @type {import('tailwindcss').Config} */
import typography from "@tailwindcss/typography";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#f0f4ff",
          100: "#e0e9ff",
          200: "#c7d4fb",
          300: "#a5b8f5",
          400: "#7a93ef",
          500: "#4f70e8",
          600: "#3d5cd4",
          700: "#2d47c0",
          800: "#243a9e",
          900: "#1a2d7a",
        },
        accent: {
          50: "#f5f3ff",
          100: "#ede9fe",
          200: "#ddd6fe",
          300: "#c4b5fd",
          400: "#a78bfa",
          500: "#8b5cf6",
          600: "#7c3aed",
          700: "#6d28d9",
        },
        success: {
          50: "#ecfdf5",
          100: "#d1fae5",
          500: "#10b981",
          600: "#059669",
          700: "#047857",
        },
        warning: {
          50: "#fffbeb",
          100: "#fef3c7",
          500: "#f59e0b",
          600: "#d97706",
          700: "#b45309",
        },
        danger: {
          50: "#fef2f2",
          100: "#fee2e2",
          500: "#ef4444",
          600: "#dc2626",
          700: "#b91c1c",
        },
        info: {
          50: "#eff6ff",
          100: "#dbeafe",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
        },
      },
      boxShadow: {
        card: "0 1px 2px 0 rgb(15 23 42 / 0.04), 0 1px 3px 0 rgb(15 23 42 / 0.06)",
        "card-hover": "0 4px 12px -2px rgb(15 23 42 / 0.10), 0 2px 6px -2px rgb(15 23 42 / 0.06)",
        pop: "0 10px 30px -6px rgb(15 23 42 / 0.18), 0 4px 12px -4px rgb(15 23 42 / 0.10)",
        glow: "0 8px 24px -6px rgb(79 112 232 / 0.45)",
      },
      borderRadius: {
        xl: "0.875rem",
        "2xl": "1.125rem",
      },
      fontFamily: {
        sans: [
          "Inter",
          "Noto Sans",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        deva: ["Noto Sans Devanagari", "Noto Sans", "system-ui", "sans-serif"],
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.25s ease-out",
        "slide-up": "slide-up 0.3s ease-out",
      },
      typography: ({ theme }) => ({
        brand: {
          css: {
            "--tw-prose-body": theme("colors.gray[700]"),
            "--tw-prose-headings": theme("colors.gray[900]"),
            "--tw-prose-bold": theme("colors.brand[700]"),
            "--tw-prose-bullets": theme("colors.brand[400]"),
            "--tw-prose-counters": theme("colors.brand[500]"),
            "--tw-prose-links": theme("colors.brand[600]"),
            "--tw-prose-quotes": theme("colors.gray[600]"),
            "--tw-prose-quote-borders": theme("colors.brand[200]"),
            "--tw-prose-hr": theme("colors.gray[200]"),
            "--tw-prose-th-borders": theme("colors.gray[300]"),
            "--tw-prose-td-borders": theme("colors.gray[200]"),
            maxWidth: "none",
            lineHeight: "1.7",
            h1: { fontWeight: "700", fontSize: "1.4em", marginTop: "1.2em", marginBottom: "0.5em" },
            h2: { fontWeight: "700", fontSize: "1.2em", marginTop: "1.1em", marginBottom: "0.4em" },
            h3: { fontWeight: "600", fontSize: "1.05em", marginTop: "1em", marginBottom: "0.3em" },
            "h1, h2, h3, h4": { lineHeight: "1.3", scrollMarginTop: "5rem" },
            p: { marginTop: "0.6em", marginBottom: "0.6em" },
            "ul, ol": { marginTop: "0.5em", marginBottom: "0.5em", paddingLeft: "1.4em" },
            "li": { marginTop: "0.2em", marginBottom: "0.2em" },
            "li::marker": { fontWeight: "600" },
            strong: { fontWeight: "700" },
            code: {
              backgroundColor: theme("colors.gray[100]"),
              padding: "0.15em 0.4em",
              borderRadius: "0.35rem",
              fontWeight: "500",
              fontSize: "0.9em",
            },
            "code::before": { content: '""' },
            "code::after": { content: '""' },
            blockquote: {
              fontStyle: "normal",
              borderLeftWidth: "3px",
              paddingLeft: "1em",
              backgroundColor: theme("colors.brand[50]"),
              borderRadius: "0 0.5rem 0.5rem 0",
              paddingTop: "0.4em",
              paddingBottom: "0.4em",
            },
            "blockquote p:first-of-type::before": { content: '""' },
            "blockquote p:last-of-type::after": { content: '""' },
          },
        },
      }),
    },
  },
  plugins: [typography],
};
