services:
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    depends_on:
      - worker

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile.worker
    env_file:
      - ../backend/.env

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
    ports:
      - "80:80"
